version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-demo-app:latest
    container_name: nginx-prod-server
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

