version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: angular-app
    volumes:
      - ./angular-calendar:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    networks:
      - nginx-network

  nginx:
    image: nginx:latest
    container_name: nginx-dev-server
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    depends_on:
      - angular-app
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
