version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./angular-calendar/dist/angular-calendar/browser:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - nginx-network

volumes:
  html-data:
    driver: local

networks:
  nginx-network:
    driver: bridge
